### ISSUE TITLE
banca are un card. cardul are o persoana... e un pic messed-up. Persoana are un card care foloseste o banca probabil e mai ok

### ISSUE THREAD

**Issue by stefanbulzan** [RazvanTurc/curs8-Homework#4]
https://github.com/RazvanTurc/curs8-Homework/blob/5341d0ed881490eb39e3939a8fb6069a119d82fb/src/ro/fasttrackit/curs8/homework2/banks/BankBRD.java#L11

**Comment by RazvanTurc** [comment]
Am incercat sa remediez problema. Mi-a dat ceva batai de cap... inca sunt sigur ca ceva nu e bine dar nu pot sa observ ce anume..
