### ISSUE TITLE
e mult mai bun designul asta. Ce ti-a ramas e ca ceri date cu Scannerul din BankBRD... BankBRD trebuie sa se ocupe doar cu date, si sa primeasca parametrii, nu trebuie sa stie cum se iau datele... Scannerul e in Main sau alt obiect

### ISSUE THREAD

**Issue by stefanbulzan** [RazvanTurc/curs8-Homework#8]
https://github.com/RazvanTurc/curs8-Homework/blob/fee91d96dfde029e0651c928c1ecdb478f172c5e/src/ro/fasttrackit/curs8/homework2/banks/BankBRD.java#L8

**Comment by RazvanTurc** [comment]
Nu stiu daca am facut bine... Nu stiu in ce alt mod sa pot bloca cardul dupa 3 incercari fara a face in BankETC un while in care trebuie updatat PIN-ul...
